name: Update Daily Quote

on:
  schedule:
    - cron: '0 7 * * *'  # 每天 UTC 07:00 執行（等於愛爾蘭上午 8 點）
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python update_judgement.py
